### ISSUE TITLE
Cleanup Kubeflow Testgrid

### ISSUE THREAD

**Issue by scottilee** [kubeflow/testing#460]
https://testgrid.k8s.io/sig-big-data could use some attention. @jlewi Let me know what you think about the following tasks and questions:

**Tasks**
1. Remove unused jobs from https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubeflow (e.g., `kubeflow-periodic-0-4-branch` and `kubeflow-periodic-0-3-branch`
2. Remove unused groups from https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubeflow/kubeflow.yaml (please refer to the 1st question below)
3. Move Kubeflow-specific tests under a "Kubeflow" dashboard tab to separate them from spark-related tests by editing the testgrids config and updating testgrid-dashboard annotations under the jobs configs

**Questions**
1. The following tabs are void of tests, should any of them be removed from the jobs config or testgrids config?
- [ ] `kubeflow-kfctl-postsubmit`
- [ ] `kubeflow-chainer-operator-postsubmit`
- [ ] `kubeflow-kfctl-postsubmit`
- [ ] `kubeflow-kubebench-postsubmit`
- [ ] `kubeflow-experimental-seldon-postsubmit`
- [x] ~~`kubeflow-experimental-beagle-postsubmit`~~
- [ ] `kubeflow-mxnet-operator-postsubmit`
- [ ] `kubeflow-caffe2-operator-postsubmit`
- [ ] `kubeflow-examples-postsubmit`
- [ ] `kubeflow-mpi-operator-presubmit`
- [ ] `kubeflow-katib-postsubmit`
- [ ] `kubeflow-katib-presubmit`
- [ ] `kubeflow-kubebench-presubmit`
- [ ] `kubeflow-website-presubmit`
- [ ] `kubeflow-experimental-seldon-presubmit`
- [ ] `kubeflow-caffe2-operator-presubmit`
- [ ] `kubeflow-chainer-operator-presubmit`
- [ ] `kubeflow-reporting-presubmit`
- [x] ~~`kubeflow-experimental-kvc-presubmit`~~
- [x] ~~`kubeflow-experimental-kvc-postsubmit`~~
- [ ] `kubeflow-mxnet-operator-presubmit`
- [ ] `kubeflow-kfserving-presubmit`
- [x] ~~`kubeflow-experimental-beagle-presubmit`~~
- [ ] `kubeflow-arena-presubmit`
2. In addition to the third task above, similar tests could be grouped together under tabs (e.g, https://testgrid.k8s.io/istio-client-go). Should any of the test be grouped under tabs like "applications" or "periodics" or "kfctl"?

**Comment by jlewi** [comment]
Thanks @scottilee I think we can remove any test grids related to releases prior to v0.5.

A kubeflow specific test grid as opposed to big data sounds like a great idea

We can remove testgrids if the repository no longer exists in kubeflow or if the repository has been archived.

If the repository still exists then eventually we will want testgrids for pre, post and periodic because pretty much every repo should be doing all 3.


> In addition to the third task above, similar tests could be grouped together under tabs (e.g, https://testgrid.k8s.io/istio-client-go). Should any of the test be grouped under tabs like "applications" or "periodics" or "kfctl"?

What is a tab in this context?

**Comment by scottilee** [comment]
@jlewi 

If you go to https://testgrid.k8s.io/istio-tests-postsubmit for example, by tab I mean "Summary" or "build_tests_postsubmit" or "lint_tests_postsubmit". You can see related tests are grouped under those tabs. I was asking if we should group similar Kubeflow tests under tabs like "periodics" or "kfctl", what do you think?

Also when you say "kubeflow specific test grid" do you want me to create a new box on https://testgrid.k8s.io/ so it says kubeflow so it's no longer under "sig-big-data" (option A)? What I was going to do was keep Kubeflow under "sig-big-data" but put it in its own dashboard, like if you go to https://testgrid.k8s.io/ and hover over "sig-storage" you'll see boxes pop up (option B). Let me whether you prefer option A or B.

Also, should I add a job for the upcoming 0.7 release (`kubeflow-periodic-0-7-branch`)?

**Comment by jlewi** [comment]
Option B seems fine to me. 

Yes a job for the upcoming release would be great.

**Comment by scottilee** [comment]
I went through the Kubeflow repos and it looks like `kubeflow-experimental-beagle-postsubmit`, `kubeflow-experimental-kvc-presubmit`, `kubeflow-experimental-kvc-postsubmit`, and `kubeflow-experimental-beagle-presubmit` are no longer repositories. I will remove them and have checked them off above.

I'm going to wait until https://github.com/kubernetes/test-infra/issues/14343 is resolved before continuing on this ticket although I have changes ready to push for a PR.
